# Generated by Django 4.0 on 2021-12-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
